---
title: "R Notebook"
output: html_notebook
---
```{r}
set.seed(20220106)
library(SpatialPCA)
library(ggplot2)
getwd()
```


```{r}
i=9 # use sample 9 as an example
load(paste0("../raw_data/DLPFC/LIBD_sample",i,".RData") ) 
dataset=paste0("LIBD_sample",i,"_SpatialPCA")
clusterNum=c(7,7,7,7,5,5,5,5,7,7,7,7)

# use small number of samples for testing
count_sub <- count_sub[,1:2000 ]
xy_coords <- xy_coords[1:2000, ]

print(dim(count_sub)) # The count matrix
print(dim(xy_coords)) # The x and y coordinates. We flipped the y axis for visualization.

```

```{r}
xy_coords = as.matrix(xy_coords)
rownames(xy_coords) = colnames(count_sub)

# select 500 gene for testing. 
LIBD = CreateSpatialPCAObject(counts=count_sub, location=xy_coords, project = "SpatialPCA",gene.type="spatial",sparkversion="sparkx",numCores_spark=5,gene.number=500, customGenelist=NULL,min.loctions = 20, min.features=20)
LIBD = SpatialPCA_buildKernel(LIBD, kerneltype="gaussian", bandwidthtype="SJ",bandwidth.set.by.user=NULL)
```

```{r}
truth = KRM_manual_layers_sub$layer_guess_reordered[match(colnames(LIBD@normalized_expr),colnames(count_sub))]
saveRDS(truth, "../pro_data/DLPFC/truth_dlpfc.rds")
saveRDS(LIBD@normalized_expr, "../pro_data/DLPFC/norm_exp_dlpfc.rds")
saveRDS(LIBD@location, "../pro_data/DLPFC/location_dlpfc.rds")
```


```{r}
start_time <- Sys.time()
LIBD = SpatialPCA_EstimateLoading(LIBD,fast=FALSE,SpatialPCnum=5, maxiter=100)
end_time <- Sys.time()
T = end_time - start_time
T
```

```{r}
LIBD = SpatialPCA_SpatialPCs(LIBD, fast=FALSE)
```

```{r}
clusterlabel= walktrap_clustering(clusternum=clusterNum[i],latent_dat=LIBD@SpatialPCs,knearest=70 ) 
# here for all 12 samples in LIBD, we set the same k nearest number in walktrap_clustering to be 70. 
# for other Visium or ST data, the user can also set k nearest number as round(sqrt(dim(SpatialPCAobject@SpatialPCs)[2])) by default.
clusterlabel_refine = refine_cluster_10x(clusterlabels=clusterlabel,location=LIBD@location,shape="hexagon")
saveRDS(clusterlabel_refine, '/Users/eugene/SpaPCA_python/spa_PCA_r/env_rds/dlpfc_r_cluster.rds')
```

```{r}
cbp=c("#9C9EDE" ,"#5CB85C" ,"#E377C2", "#4DBBD5" ,"#FED439" ,"#FF9896", "#FFDC91")
spapca_img <- plot_cluster(location=xy_coords,clusterlabel=clusterlabel_refine,pointsize=1.5 ,title_in=paste0("SpatialPCA"),color_in=cbp)
spapca_img
ggsave(spapca_img, filename = "../fig/dlpfc_spapca.svg", width = 10, height = 6, units = "in", dpi = 300)
```

```{r}
truth = KRM_manual_layers_sub$layer_guess_reordered[match(colnames(LIBD@normalized_expr),colnames(count_sub))]
cbp=c("#5CB85C" ,"#9C9EDE" ,"#FFDC91", "#4DBBD5" ,"#FF9896" ,"#FED439", "#E377C2", "#FED439")
truth_dlpfc <- plot_cluster(location=xy_coords,truth,pointsize=1.5,title_in=paste0("Ground truth"),color_in=cbp)
truth_dlpfc
ggsave(truth_dlpfc, filename = "../fig/dlpfc_truth.svg", width = 10, height = 6, units = "in", dpi = 300)
```



